imports:
    - php

tools:
    php_changetracking: true
    php_sim:
        min_mass: 30
    php_pdepend: true
    php_mess_detector: true
    php_hhvm: true
    php_analyzer: true
    php_cs_fixer: true
    sensiolabs_security_checker: true
    external_code_coverage:
        timeout: 600 # Timeout in seconds.
