language: php

php:
- 7.2
- nightly

sudo: false

script:
- ./vendor/bin/parallel-lint ./src/
- ./vendor/bin/phpcs -n -p --standard=PSR2 --extensions=php,twig ./src/
- ./vendor/bin/php-cs-fixer fix -v ./src --dry-run

notifications:
  email:
  - info@jield.nl

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly