<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'affiliation/community/affiliation'    => __DIR__ . '//view/affiliation/community/affiliation.twig',
    'affiliation/community/edit'           => __DIR__ . '//view/affiliation/community/edit.twig',
    'affiliation/doa/upload'               => __DIR__ . '//view/affiliation/doa/upload.twig',
    'affiliation/loi/upload'               => __DIR__ . '//view/affiliation/loi/upload.twig',
    'affiliation/partial/form/affiliation' => __DIR__ . '//view/affiliation/partial/form/affiliation.twig',
    'affiliation/pdf/doa-project'          => __DIR__ . '//view/affiliation/pdf/doa-project.twig',
    'affiliation/pdf/loi-project'          => __DIR__ . '//view/affiliation/pdf/loi-project.twig',
);
