<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'affiliation/community/affiliation'        => __DIR__ . '//view/affiliation/community/affiliation.twig',
    'affiliation/community/edit'               => __DIR__ . '//view/affiliation/community/edit.twig',
    'affiliation/community/upload-program-doa' => __DIR__ . '//view/affiliation/community/upload-program-doa.twig',
    'affiliation/partial/form/affiliation'     => __DIR__ . '//view/affiliation/partial/form/affiliation.twig',
);
