<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'affiliation/affiliation/affiliation'  => __DIR__ . '/../../view/affiliation/affiliation/affiliation.twig',
    'affiliation/partial/form/affiliation' => __DIR__ . '/../../view/affiliation/partial/form/affiliation.twig',
);
