<?php
_("txt-date-signed");
_("txt-date-approved");
_("txt-branch");
_("txt-note");
_("txt-value-chain");
_("txt-market-access");
_("txt-strategic-importance");
_("txt-main-contribution");
_("txt-self-funded");
_("txt-date-end");
_("txt-date-self-funded");
_("txt-project-leader");
_("txt-ict-organisation");
_("txt-associates");
_("txt-not-self-funded");
_("txt-affiliation-description");
_("txt-affiliation-description-explanation");