<?php
_("txt-give-document-name");
_("txt-affiliation-description");
_("txt-affiliation-description-explanation");
_("txt-deactivate-partner-%s-button");
_("txt-reactivate-partner-%s-button");
_("txt-affiliation-%s-has-been-deactivated-on-%s-date");
_("txt-update-costs");
_("txt-deactivation-of-partner-is-disabled-remove-cost-and-effort-in-draft-first");
